### ISSUE TITLE
Load Player Account Error

### ISSUE THREAD

**Issue by DevTimmOfTO** [Tech-Roleplay/tr-World#1]
The Error
```bash
[11:11:05][Error] ERROR == ERROR == ERROR
[11:11:05][Error] System.InvalidOperationException: This MySqlConnection is already in use. See https://fl.vu/mysql-conn-reuse
   at MySqlConnector.Core.ServerSession.StartQuerying(ICancellableCommand command)
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.MySqlCommand.ExecuteReader()
   at tr_world.Controllers.JobController.LoadJobDetailsFromDb(String jobname) in S:\tr-world\mainserver\backend\tr-world\tr-world\Controllers\JobController.cs:line 24
[11:11:05][Error] ERROR == ERROR == ERROR
[11:11:05][Error] System.InvalidOperationException: This MySqlConnection is already in use. See https://fl.vu/mysql-conn-reuse
   at MySqlConnector.Core.ServerSession.StartQuerying(ICancellableCommand command)
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.MySqlCommand.ExecuteReader()
   at tr_world.Controllers.JobController.LoadJobGradeFromDb(String jobname, Int32 grade) in S:\tr-world\mainserver\backend\tr-world\tr-world\Controllers\JobController.cs:line 56
[11:11:05][Error] ERROR == ERROR == ERROR
[11:11:05][Error] System.NullReferenceException: Object reference not set to an instance of an object.
   at tr_world.Controllers.BPlayerController.LoadBPlayerData(BPlayer player, String CharId) in S:\tr-world\mainserver\backend\tr-world\tr-world\Controllers\BPlayerController.cs:line 73

``` 

Completed:
```bash
S:/tr-world/mainserver/altv-server.exe
[11:10:29] alt:V Server 16.2.1 (release)
[11:10:29] Starting My server name on [::]:7788
[11:10:29] Loading resource tr-world
[11:10:29] Loading resource chat
[11:10:30] Loaded resource chat
[csharp-module] Checking dependencies... this might take a few minutes...
[11:10:34] Server-C#-backend is starting!
[11:10:35][Warning] MYSQL connection established successfully!
[11:10:35] Loaded resource tr-world
[11:10:35] Loading resource altv-indicators
[11:10:35][Error] Could not open resource config
[11:10:35][Error] Failed to load resource altv-indicators
[11:10:35] Required server permissions:
[11:10:35] Optional server permissions:
[11:10:35] Starting HTTP server on [::]:7788
[11:10:35] Main thread started (ThreadId: 40556)
[11:10:35] EntityStreamer thread started (ThreadId: 3328)
[11:10:35] SyncSend thread started (ThreadId: 14344)
[11:10:35] SyncSend thread started (ThreadId: 24684)
[11:10:35] SyncSend thread started (ThreadId: 47816)
[11:10:35] SyncSend thread started (ThreadId: 33724)
[11:10:35] SyncSend thread started (ThreadId: 35204)
[11:10:35] SyncSend thread started (ThreadId: 11220)
[11:10:35] SyncSend thread started (ThreadId: 41500)
[11:10:35] SyncSend thread started (ThreadId: 40856)
[11:10:35] NetworkWorker #1 thread started (ThreadId: 46608)
[11:10:35] SyncReceive thread started (ThreadId: 44832)
[11:10:35] SyncReceive thread started (ThreadId: 28620)
[11:10:35] Console thread started (ThreadId: 43860)
[11:10:35][Warning] Server started in debug mode
[11:10:49] [1] The Player TheBlokker has joined the Server. Discord-ID is: 629199560002109453. Welcome.
[11:11:05][Error] ERROR == ERROR == ERROR
[11:11:05][Error] System.InvalidOperationException: This MySqlConnection is already in use. See https://fl.vu/mysql-conn-reuse
   at MySqlConnector.Core.ServerSession.StartQuerying(ICancellableCommand command)
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.MySqlCommand.ExecuteReader()
   at tr_world.Controllers.JobController.LoadJobDetailsFromDb(String jobname) in S:\tr-world\mainserver\backend\tr-world\tr-world\Controllers\JobController.cs:line 24
[11:11:05][Error] ERROR == ERROR == ERROR
[11:11:05][Error] System.InvalidOperationException: This MySqlConnection is already in use. See https://fl.vu/mysql-conn-reuse
   at MySqlConnector.Core.ServerSession.StartQuerying(ICancellableCommand command)
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.MySqlCommand.ExecuteReader()
   at tr_world.Controllers.JobController.LoadJobGradeFromDb(String jobname, Int32 grade) in S:\tr-world\mainserver\backend\tr-world\tr-world\Controllers\JobController.cs:line 56
[11:11:05][Error] ERROR == ERROR == ERROR
[11:11:05][Error] System.NullReferenceException: Object reference not set to an instance of an object.
   at tr_world.Controllers.BPlayerController.LoadBPlayerData(BPlayer player, String CharId) in S:\tr-world\mainserver\backend\tr-world\tr-world\Controllers\BPlayerController.cs:line 73
[11:11:05] [chat:cmd] TheBlokker: /loadBPlayer ABC-159
```

**Comment by DevTimmOfTO** [comment]
Fixed in commit
https://github.com/Tech-Roleplay/tr-World/commit/35884d5c7e9184d6d5f46c0f1d67999ea634c362
